from . import kser_beneficiary
from . import kser_cash_donation
from . import kser_audit_log
from . import res_partner
from . import res_config_settings
from . import stock_picking
from . import stock_move
from . import project_task
from . import project_project
from . import account_move
from . import product_template
from . import kser_prescription
from . import kser_prescription_line
from . import kser_child_followup
from . import kser_clinic_visit
from . import res_users
from . import kser_chronic_condition
